<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo $page_title; ?></title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo WEB_ROOT . 'css/bootstrap/bootstrap.min.css'; ?>" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="<?php echo WEB_ROOT . 'css/layouts/nolayout.css'; ?>" rel="stylesheet">
    <link href="<?php echo WEB_ROOT . 'css/style.css'; ?>" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
<?php echo $content_view ?>
</body>
</html>
